version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    volumes:
      - ./:/assignment
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fastapi_assignment
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:4306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: