"""empty message

Revision ID: a6ef9ca6ead6
Revises: 1e3183369491
Create Date: 2022-09-30 15:09:59.954775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ef9ca6ead6'
down_revision = '1e3183369491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    # ### end Alembic commands ###
